### ISSUE TITLE
Modifications not reflected in LDAP

### ISSUE THREAD

**Issue by dwgnr** [th-nuernberg/usermgmt#1]
Tried adding `gpuultimate` QOS to a user via:

```bash
usermgmt modify $username --qos advanced bigmem gpubasic interactive ultimate gpuultimate
```

QOS was sucessfully added in Slurm (verified via `sacctmgr show assoc user=$username format=user,qos%50`) but was not added in LDAP. 

Remote and local execution both seem affected. 

Also: We need a proper error message for this. Output said:

```bash
[INFO  usermgmt::ldap::ldap] Successfully modified user xy in LDAP
```

**Comment by BoolPurist** [comment]
Fixed by PR #42
