### ISSUE TITLE
It should be possible to develop the app while it accesses a local open LDAP instance in docker.

### ISSUE THREAD

**Issue by BoolPurist** [th-nuernberg/usermgmt#11]
These allows for testing/developing the app without risking damage to production data and enables development of this app for user without privileges for changing user on the production LDAP instance. 

There is a docker image which allows starting an open LDAP instance. See [here](https://github.com/osixia/docker-openldap).

**Comment by BoolPurist** [comment]
To develop this application completely locally. 
The following aspects must be handled in docker container:

- Ldap 
  - Must have Scheme for Slurm job 
  - Dummy users must have public ssh key 
- ssh
  - should listen to ssh client and retrieve public ssh key from ldap db
- Slurm
   - must have the Slurm manager executable,
   - must have Slurm database for Slurm users.
- Directories 
  - over ssh certain commands must be executable like creating directory
  - NFS server ?
  - Settting quotes for directory.

Pull request to handel this issure https://github.com/th-nuernberg/usermgmt/pull/17

**Comment by dwgnr** [comment]
There are also some Docker solutions for setting up Slurm clusters (e.g. https://github.com/giovtorres/slurm-docker-cluster or https://hub.docker.com/r/popperized/docker-slurm-cluster). 
Maybe we try creating an entire Docker-based test environment?

I suppose the directory management can also be done via Docker. 
We would only need to configure quota on some mountpoint and run the directory management against it.

**Comment by BoolPurist** [comment]
It is possible to create docker base slurm environment. Needs to some work however with https://github.com/giovtorres/slurm-docker-cluster. See pull request for details #17
