### ISSUE TITLE
Next uid for user to be added is not found if no users added far.

### ISSUE THREAD

**Issue by BoolPurist** [th-nuernberg/usermgmt#15]
When trying to add an user in a ldap database with no users so far then the app errors with no guid found.

I tested that with a docker container with no users to begin with.

My suggestion would be to provide an uid number starting from 10001 for students and 1001 for staff if no user were added so far.

It comes down to the code snippet which determines the next uid for the user to be added. [Secion](https://github.com/th-nuernberg/usermgmt/blob/main/src/util.rs) starting at line 21.

**Comment by dwgnr** [comment]
This is likely an edge case in prod but probably matters a lot when starting a fresh ldap instance in docker. 
Your suggestion seems reasonable.

**Comment by BoolPurist** [comment]
[Pull request](https://github.com/th-nuernberg/usermgmt/pull/16) to fix this issue.
