### ISSUE TITLE
Inconsistent CLI API.

### ISSUE THREAD

**Issue by BoolPurist** [th-nuernberg/usermgmt#24]
# Problems in the CLI API

CLI API subcommand, option flags and positional arguments, has some problems in the area of consistency and flexibility.

## Problems in consistency: 

- Not every sub command uses all of the 3 arguments, "--ldap-only",  "--slurm-only" and "--dirs-only" for all sub commands.
  Example the sub command **list** only works on LDAP user or Slurm users. 
- Options for ldap and slurm is redundant in sub command **list** with option flags "--ldap-users" and "--slurm-users".
- Directory management can also be deactivated via conf.toml but not LDAP or Slurm. 

## Problems in flexibility:

- One can only go all 3 options LDAP, Slurm and directory management or only for 1 option.
  It is not possible to go for example LDAP and Slurm but not directory management.

## Proposed fixes for inconsistency

- the options for LDAP, Slurm and Directory Management should be specified under the sub command respectively.
  Example: Sub command "add" allows all 3 and sub command "list" allows only LDAP and Slurm.
- Either remove key "include_dir_mgmt" or add additional keys for LDAP and Slurm in conf.toml. 
  - Or add "include_slurm" and "include_ldap". Then the CLI options should have priority over config values. Example: If CLI options is true then the corresponding value in conf.toml being false is ignored.

## Proposed fixes in Fexibility

- if none of the options like LDAP, Slurm and directory management are given, then all are considered . If at least one 
   option is given, only given options are considered. Example option **--ldap** and **--slurm** are given then LDAP 
   and Slurm are considered. 
- Only options aka "--ldap-only" are replaced by opt ins "--ldap" options.

**Comment by dwgnr** [comment]
Do it

**Comment by BoolPurist** [comment]
Was implemented via PR https://github.com/th-nuernberg/usermgmt/pull/38
