### ISSUE TITLE
Make SSH port for client connections configurable

### ISSUE THREAD

**Issue by dwgnr** [th-nuernberg/usermgmt#30]
The default port for SSH client connections is hardcoded in several places (e.g. [here](https://github.com/th-nuernberg/usermgmt/blob/3b5efea1cb608a3f4f23840577bfc6d8ff5bde0c/src/slurm.rs#L185)). 

The port should be configurable via `conf.toml` to allow for non-standard ports.

**Comment by BoolPurist** [comment]
@dwgnr  this was implemented via this PR https://github.com/th-nuernberg/usermgmt/pull/32
