### ISSUE TITLE
Allow serveral possible paths to get configuration file in production.

### ISSUE THREAD

**Issue by BoolPurist** [th-nuernberg/usermgmt#56]
## Purpose

In the moment of writing this issue, the folder "/etc/usermgmt" is checked in production only. 
This causes some problems.

1. Release version of the application on machines which are not server for example laptops, need root access to this folder on most systems.
2. There are dedicated places which should also be usuable on usual OS Systems in production. 

## Details

- Checking serveral places in the following order: 
  - "usr/config.toml" on linux.
  - The respective path for user config on a platform. For example under folder ~/user/.config/usermagmt for linux.
    There is also a crate called "dirs" to help with that. Link: https://docs.rs/dirs/latest/dirs/.
  - Current working directory. 
- New subcommand to generate default configuation file in current working directory in production.

**Comment by BoolPurist** [comment]
@dwgnr Would do yout think about it ?

**Comment by dwgnr** [comment]
I think that's a great idea. 
I would suggest to look under `~/.usermgmt/` last. This is a commonly used location for these types of configs (see e.g. [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html), which places the user config under `~/.aws`). The `/etc/usermgmt` dir should remain a valid path for the config file though. It makes sense as a global configuration location in case someone provides a system-wide installation (which we currently do on our control node). The user could still override the global config with a file placed in `~/.usermgmt/`, if they prefer some custom settings.

**Comment by BoolPurist** [comment]
Implemented by PR #58
