### ISSUE TITLE
Logging to file for usermgmt GUI Version

### ISSUE THREAD

**Issue by BoolPurist** [th-nuernberg/usermgmt#70]
Change logging in a way so that the logging also goes to a file. This can be useful if end users report bugs with written logs in a file.

**Comment by BoolPurist** [comment]
The following crate could be a good replacement for env_logger. 

- [flexi_logger](https://crates.io/crates/flexi_logger) provides logging to files in a seperate thread. Prevents GUI application from freezing.

**Comment by BoolPurist** [comment]
When comes down to where save the logging as a text file.
-
- The application should always log to stderr too.
- It should try to save under the typical data folder on certain OS. For example "~/.local/share/name_of_application".
- If that fails as a location for the logging file, should it try to save the output at the same folder of executable ? @dwgnr

**Comment by dwgnr** [comment]
Save the output in same directory as the executable sounds good.

**Comment by BoolPurist** [comment]
Solved by #77
