### ISSUE TITLE
Write some docs

### ISSUE THREAD

**Issue by dwgnr** [th-nuernberg/usermgmt#74]

**Comment by dwgnr** [comment]
kthxbye

**Comment by BoolPurist** [comment]
One important thing is that most public functions do not have any API documentation. 

The following are points should be in an API documentation for rust function.

- Summary: What it can be used for.
- Error section: In case the function returns a result value. This section describes which condition lead to an error variant.
- None section: In case the function returns a option value. This section describes which condition lead to a None variant.

**Comment by BoolPurist** [comment]
Done by PR https://github.com/th-nuernberg/usermgmt/pull/81
