### ISSUE TITLE
add speech recognition to test10

### ISSUE THREAD

**Issue by ChipCracker** [th-nuernberg/usermgmt#82]

**Comment by BoolPurist** [comment]
What do you mean by test10, a cluster/node or user ?

**Comment by dwgnr** [comment]
I guess this was opened by accident?

**Comment by dwgnr** [comment]
Seems to belong to https://github.com/th-nuernberg/memtest. Closing.

**Comment by ChipCracker** [comment]
Sorry, that was an oversight. I unfortunately assigned the ticket incorrectly.
